name: Challenge response
description: Challenge response
title: "🚀 Response: "
body:
  - type: markdown
    attributes:
      value: |
        Congratulations on your commitment to answering this challenge!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Enter your email in case I need to contact you for more information
      placeholder: email@example.com
    validations:
      required: true
  - type: textarea
    id: describe-answer
    attributes:
      label: Describe your answer
      description: A clear and concise description of your answer
      placeholder: "Type here"
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: Please tell us the step by step that you have done
      placeholder: "Type here"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you think would happen?
      placeholder: "Type here"
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What did actually happen? Add screenshots, if applicable?
      placeholder: "it actually ..."
    validations:
      required: true
